### ISSUE TITLE
How to purge cache?

### ISSUE THREAD

**Issue by HarpreetHeera** [NiveditJain/BunnyCDNStorageLib#3]
Hi 
Thanks for providing python API for Bunny CDN..
Please help in providing function for purging files of a zone.
Regards
Harpreet

**Comment by NiveditJain** [comment]
Hi @HarpreetHeera 
We have made a better SDK at https://github.com/mathrithms/BunnyCDN-Python-Lib
It has purge functionality. 

Thanks and Regards.

**Comment by HarpreetHeera** [comment]
Awesome.
Thanks for quick response and great work.
Many thanks:)
